{{- $nak := .Values.nvidiaApiKey | default dict }}
{{- if and $nak.create $nak.name $nak.password }}
{{- $ngcUser := $nak.username }}
{{- $reg := $nak.registry }}
{{- $auth := printf "%s:%s" $ngcUser $nak.password | b64enc }}
{{- $config := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $reg $ngcUser $nak.password $auth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $nak.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $config | b64enc | quote }}
  NGC_API_KEY: {{ $nak.password | b64enc | quote }}
  NVIDIA_API_KEY: {{ $nak.password | b64enc | quote }}
{{- end }}
