apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: {{ .Values.grafana.namespace }}
  annotations:
    kubernetes.io/service-account.name: grafana-sa
type: kubernetes.io/service-account-token
